src/Entity/Ticket.php
<?php

namespace App\Entity;

use App\Repository\TicketRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TicketRepository::class)]
class Ticket
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column(length: 100)]
    private ?string $ticketType = null;

    #[ORM\ManyToOne(inversedBy: 'tickets')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Event $event = null;

    #[ORM\OneToMany(mappedBy: 'ticketNumber', targetEntity: Purchase::class)]
    private Collection $purchases;

    #[ORM\Column(nullable: true)]
    private ?int $ticket_limit = null;

    public function __construct()
    {
        $this->purchases = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getTicketType(): ?string
    {
        return $this->ticketType;
    }

    public function setTicketType(string $ticketType): static
    {
        $this->ticketType = $ticketType;

        return $this;
    }

    public function getEvent(): ?Event
    {
        return $this->event;
    }

    public function setEvent(?Event $event): static
    {
        $this->event = $event;

        return $this;
    }

    /**
     * @return Collection<int, Purchase>
     */
    public function getPurchases(): Collection
    {
        return $this->purchases;
    }

    public function addPurchase(Purchase $purchase): static
    {
        if (!$this->purchases->contains($purchase)) {
            $this->purchases->add($purchase);
            $purchase->setTicketNumber($this);
        }

        return $this;
    }

    public function removePurchase(Purchase $purchase): static
    {
        if ($this->purchases->removeElement($purchase)) {
            // set the owning side to null (unless already changed)
            if ($purchase->getTicketNumber() === $this) {
                $purchase->setTicketNumber(null);
            }
        }

        return $this;
    }

    public function getTicketLimit(): ?int
    {
        return $this->ticket_limit;
    }

    public function setTicketLimit(?int $ticket_limit): static
    {
        $this->ticket_limit = $ticket_limit;

        return $this;
    }
}

src/Controller/TicketController.php
<?php

namespace App\Controller;

use App\Entity\Ticket;
use App\Form\TicketFormType;
use App\Repository\EventRepository;
use App\Repository\TicketRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGenerator;

class TicketController extends AbstractController
{
    #[Route('/ticket/créer/{id}', name: 'app_ticket')]
    public function index(Request $request, $id, EntityManagerInterface $em, EventRepository $eventRepository, TicketRepository $ticketRepository): Response
    {
        $ticket = new Ticket();
        $event = $eventRepository
            ->find($id);
        $ticket->setEvent($event);
        $ID = $event->getId();
        $tickets = $ticketRepository->findBy([
            'event' => $event
        ]);

        $ticketForm = $this->createForm(TicketFormType::class, $ticket);
        $ticketForm->handleRequest($request);

        if($ticketForm->isSubmitted() && $ticketForm->isValid()){
            $em->persist($ticket);
            $em->flush();

            return $this->redirectToRoute('app_ticket', ['id' => $ID]);
        }

        return $this->render('ticket/index.html.twig', [
            'ticketForm' => $ticketForm->createView(),
            'tickets' => $tickets,
        ]);
    }
}

templates/ticket/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TicketController!{% endblock %}

{% block body %}
<section class="container">
    <div class="row">
        <div class="col-12">
            <h1>Créer vos billets</h1>
        </div>
        <div class="col-6">
                {{ form_start(ticketForm) }}
                {{ form_row(ticketForm.ticketType) }}
                {{ form_row(ticketForm.price) }}
                {{ form_row(ticketForm.ticket_limit) }}
                <button type="submit" class="btn btn-lg btn-primary">Créer</button>
                <a href="{{ path('organisateur_place') }}" class="btn btn-lg btn-warning">Terminé</a>
            {{ form_end(ticketForm) }}
        </div>
        <div class="col-6">
            <h3>Mes billets</h3>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Type de billet</th>
                        <th>Prix</th>
                        <th>Limite</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ticket in tickets %}
                        {% if ticket == null %}
                            <h5>Aucun ticket existant</h5>
                            {% else %}
                                <tr>
                                    <td>{{ ticket.ticketType }}</td>
                                    <td>{{ ticket.price }}</td>
                                    <td>{{ ticket.ticketLimit }}</td>
                                </tr>                      
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>
{% endblock %}